apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsuru
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - pods/attach
  - pods/exec
  - nodes
  - services
  - namespaces
  - serviceaccounts
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - "*"

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  verbs:
  - "*"

- apiGroups:
  - policy
  resources:
  - pods/eviction
  verbs:
  - create

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get

- apiGroups:
  - tsuru.io
  resources:
  - apps
  verbs:
  - "*"
